"use client"

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/navbar";
import LoginForm from "./components/form/login";
import { useSession } from "@/lib/auth-client";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { TabsContent } from "@radix-ui/react-tabs";
import RegisterForm from "./components/form/register";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Admin",
  description: "Generated by create next app",
};

const userLogged = {
  username: "",
  password: ""
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {

  const session = useSession()

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <main>
          {
            !session.data?.user.name || !session.data.user.email
            ? <Tabs defaultValue="login" className="max-w-md mx-auto mt-10">
                <TabsList className="grid w-full grid-cols-2">
                  <TabsTrigger value="login">Iniciar sesión</TabsTrigger>
                  <TabsTrigger value="register">Registrarse</TabsTrigger>
                </TabsList>
                <TabsContent value="login">
                  <LoginForm />
                </TabsContent>
                <TabsContent value="register">
                  <RegisterForm />
                </TabsContent>
              </Tabs> 
            : <><Navbar />{children}</>
          }
        </main>
      </body>
    </html>
  );
}
